trigger:
-main

Pool:
 vmImage:'windows latest'
 
steps:
 -script: echo 'Hello  World'
 displayName: 'Run Hello world Script'

 -script: |
    echo 'Checking files'
    ls - la
  displayName: 'List Files'

 
 -task: CopyFiles@2
  displayName: 'Copy Application Files'
  inputs:
   SourceFolder: '$(Build.SourceDirectory)/app'
   contents: '**'
   TargetFolder: '$(Build.ArtifactStagingDirectory)/app'

 -task: PublishBuildArtifact@1
  displayName: 'Publish Artifact'
  inputs:
   PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
   ArtifactName: 'Myapp'
   publishLocation: 'Container'
